### ISSUE TITLE
提案:postに関してはif文で分けるのはどうか

### ISSUE THREAD

**Issue by gorira-tatsu** [perify/LIKE#14]
## 改善詳細 / Details of Improvement
- flaskの文をif文で分けてみる

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by saladbowl77** [comment]
```python
@app.route("/hoge", methods=["GET", "POST"])
def hoge():
    if request.method == "POST":
        print("ここはPOST")
    else:
        print("ここはGET")
```
(ご参考にでも.. by 提案者

**Comment by gorira-tatsu** [comment]
なるほどなるほど....
そうした方が美しかも.....
なんとかします

**Comment by saladbowl77** [comment]
ただあまりにも長くなるのであれば分けて書いたほうが綺麗になると思うので例えばPOST限定だけどGETの時に何かテンプレを表示したいとかならこっちの方がいいかも

**Comment by gorira-tatsu** [comment]
うーんコードはこのままでええかなぁ....
